runtime: nodejs10
handlers:

- url:  /(/*\..+)$
  secure: always
  static_files: build/\1
  upload: build/(.*\..+)$

- url:  /.*
  secure: always
  static_files: build/index.html
  upload: build/index.html